#!/usr/bin/env python3
"""Post-close KPI threshold checker.

Reads test_summary.json, grep_assertions.json, and replay_summary.json
from artifacts/, checks against environment-variable thresholds, and
opens a GitHub issue via `gh` CLI if any threshold is breached.
"""
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ART = ROOT / "artifacts"


def load_json(name: str) -> dict:
    p = ART / name
    if p.exists():
        return json.loads(p.read_text())
    return {}


def main() -> None:
    breaches: list[str] = []
    details: list[str] = []

    # ── Check test summary ────────────────────────────────────────
    test_summary = load_json("test_summary.json")
    if test_summary.get("overall") == "fail":
        failing = [
            name for name, info in test_summary.get("suites", {}).items()
            if info.get("status") != "pass"
        ]
        breaches.append("Test suite failures")
        details.append(f"Failing suites: {', '.join(failing)}")

    # ── Check replay summary ──────────────────────────────────────
    replay = load_json("replay_summary.json")
    if replay.get("status") == "fail":
        breaches.append("Replay tests failing")
        details.append(f"Replay: {replay.get('passed', 0)} passed, {replay.get('failed', 0)} failed")

    # ── Check grep assertions ─────────────────────────────────────
    grep = load_json("grep_assertions.json")
    if grep.get("overall") == "fail":
        failing_checks = [c["name"] for c in grep.get("checks", []) if not c.get("passed")]
        breaches.append("Trading invariant violations")
        details.append(f"Failing assertions: {', '.join(failing_checks)}")

    # ── Check runtime snapshot sanity ─────────────────────────────
    snapshot = load_json("runtime_config_snapshot.json")
    if snapshot.get("error"):
        breaches.append("Runtime snapshot generation failed")
        details.append(f"Error: {snapshot['error']}")
    elif snapshot.get("exploration_enabled"):
        breaches.append("Exploration is enabled (should be disabled)")

    # ── Report ────────────────────────────────────────────────────
    if not breaches:
        print("All KPI thresholds passed.")
        return

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    sha = subprocess.check_output(
        ["git", "rev-parse", "--short", "HEAD"], text=True, cwd=str(ROOT),
    ).strip()

    title = f"[Post-Close Audit] KPI breach detected — {today}"
    body_lines = [
        f"## Post-close audit — {today}",
        f"SHA: `{sha}`",
        "",
        "### Breaches",
        "",
    ]
    for b in breaches:
        body_lines.append(f"- {b}")
    body_lines.append("")
    body_lines.append("### Details")
    body_lines.append("")
    for d in details:
        body_lines.append(f"- {d}")
    body_lines.extend([
        "",
        "### Required action",
        "",
        "Review the attached post-close artifacts and fix before next trading session.",
        "",
        "---",
        "*Auto-generated by `paper-postclose-audit` workflow.*",
    ])
    body = "\n".join(body_lines)

    # Open issue via gh CLI (available in GitHub Actions)
    try:
        result = subprocess.run(
            [
                "gh", "issue", "create",
                "--title", title,
                "--body", body,
                "--label", "strategy,organism,bug",
            ],
            capture_output=True, text=True, cwd=str(ROOT),
        )
        if result.returncode == 0:
            print(f"Issue opened: {result.stdout.strip()}")
        else:
            print(f"Failed to open issue: {result.stderr}")
            # Still print the body so it's visible in CI logs
            print("--- Issue body ---")
            print(body)
    except FileNotFoundError:
        print("gh CLI not available — printing issue body to stdout")
        print(f"TITLE: {title}")
        print(body)

    # Exit non-zero so the workflow shows as failed
    sys.exit(1)


if __name__ == "__main__":
    main()
