#!/usr/bin/env bash
# Safe repo cleanup — generated by audit 2026-06-08.
# Removes ONLY untracked, regenerable artifacts. Touches NO source code and
# NO git-tracked files. Reclaims ~160 MB immediately; optional sections reclaim
# multi-GB but require your explicit opt-in (trading state / venv).
#
# Run from repo root:  bash scripts/cleanup_safe.sh
# Dry run (show only): bash scripts/cleanup_safe.sh --dry-run
set -uo pipefail
cd "$(dirname "$0")/.." || exit 1

DRY=0
[ "${1:-}" = "--dry-run" ] && DRY=1
rm_v() { if [ "$DRY" = 1 ]; then echo "would remove: $*"; else rm -rf "$@" 2>/dev/null && echo "removed: $*"; fi; }

echo "== Repo size before =="; du -sh . 2>/dev/null

echo "== 1. Python / tooling caches (regenerate automatically) =="
if [ "$DRY" = 1 ]; then
  echo "would remove: $(find . -type d -name __pycache__ 2>/dev/null | wc -l) __pycache__ dirs"
else
  find . -type d -name __pycache__ -prune -exec rm -rf {} + 2>/dev/null
fi
rm_v .mypy_cache .pytest_cache .ruff_cache .hypothesis .cache
rm_v .coverage coverage.xml

echo "== 2. Stale archive snapshots of directories that still exist =="
rm_v backend.zip tests.zip organism_brain.zip intra_control_plane_starter_kit.zip
rm_v organism_brain_forensic_snapshot_20260408T065456Z.tar.gz
rm_v organism_brain_forensic_snapshot_20260408T065456Z

echo "== 3. Stale runtime artifacts (untracked) =="
rm_v audit_trail.log          # 42 MB untracked log
rm_v staging.db               # 0-byte empty sqlite
rm_v trading_platform.db      # 0-byte empty sqlite (recreated on demand)
rm_v _AUDIT_TRASH             # quarantined stray test files from the audit session

echo "== 4. Clear stale git lock left by sandboxed git (safe; unblocks git) =="
rm_v .git/index.lock

echo "== Repo size after =="; du -sh . 2>/dev/null

cat <<'EOF'

----------------------------------------------------------------------
OPTIONAL — NOT run automatically (need your decision):

  # A) Prune rolling brain snapshots, keep last 7 days (~5.5 GB -> ~1.8 GB).
  #    These are daily 256 MB snapshots of live model/brain state.
  #    Review before running:
  #    ls -1 organism_brain_archive | sort | head -n -7 | \
  #      while read d; do rm -rf "organism_brain_archive/$d"; done

  # B) venv (2.5 GB) — rebuildable from requirements.lock. Remove only if
  #    you can re-create it:  rm -rf venv && python -m venv venv && \
  #      venv/bin/pip install -r requirements.lock

  # C) logs/ (383 MB) — rotate/trim old run logs if not needed.
----------------------------------------------------------------------
EOF
