#!/usr/bin/env bash
# Phase-2 cleanup — generated by audit 2026-06-08.
# Deletes archived reports + stale standalone docs, corrupt brain snapshots,
# stale env backups, and empty/leftover root dirs.
# PRESERVES everything load-bearing: docs/architecture, docs/runbooks,
# docs/operations, docs/setup, docs/testing, docs/blueprints, docs/engineering
# (CI reads/writes this tree), openapi.json, and the living root docs.
#
# Run from repo root:  bash scripts/cleanup_phase2.sh [--dry-run]
set -uo pipefail
cd "$(dirname "$0")/.." || exit 1
DRY=0; [ "${1:-}" = "--dry-run" ] && DRY=1
rm_v() { if [ "$DRY" = 1 ]; then echo "would remove: $*"; else rm -rf "$@" 2>/dev/null && echo "removed: $*"; fi; }

echo "== size before =="; du -sh . 2>/dev/null

echo "== 1. Archived reports (the 27 relocated + prior archive) =="
rm_v docs/archive

echo "== 2. Stale standalone docs at docs/ root (verified: zero code references) =="
rm_v docs/AUDIT_FIX_REPORT.md docs/AUDIT_FIX_REPORT_2.md docs/AUDIT_FIX_REPORT_3.md
rm_v docs/SESSION_WORK_REPORT.md docs/PLATFORM_STATUS.md
rm_v docs/overnight_review_evolution_brain.md docs/overnight_review_execution.md \
     docs/overnight_review_ml_signals.md docs/overnight_review_tick_loop.md
rm_v docs/deep-research-report.md docs/deep-research-report2.md docs/deep-research-report3.md
rm_v docs/platform_master_narrative_2026-04-19.md
rm_v docs/trading_report_2026-03-04.md docs/trading_report_2026-03-05.md \
     docs/trading_report_2026-03-06.md docs/trading_report_2026.md

echo "== 3. Corrupt brain head snapshots (named 'corrupt_head_*' — safe) =="
rm_v organism_brain/corrupt_head_20260522_152348_974623
rm_v organism_brain/corrupt_head_20260525_152238_079051
rm_v organism_brain/corrupt_head_20260525_152238_145161
rm_v organism_brain/corrupt_head_20260526_152119_344403
rm_v organism_brain/corrupt_head_20260526_152119_408238

echo "== 4. Stale env backup =="
rm_v .env.preopen_backup_20260310_235853

echo "== 5. Empty / leftover root dirs & unzipped starter kit =="
rm_v test_results data                              # empty
rm_v intra_control_plane_starter_kit               # unzipped copy of the (now-deleted) starter zip
rm_v weekend_state_and_strategy_pack_bundle        # one-off bundle snapshot

echo "== size after =="; du -sh . 2>/dev/null

cat <<'EOF'

----------------------------------------------------------------------
DELIBERATELY NOT DELETED (uncomment only if you are sure):

  # Borderline docs (no code refs, but may still be useful plans/maps):
  #   rm -f docs/decision_map.md docs/MARKET_SCANNER_EXECUTION_PLAN.md \
  #         docs/FRONTEND_SCANNER_INTEGRATION_PLAN.md

  # docs/engineering/audits — 12 MB of historical audit dumps. The engineering
  # tree is touched by CI (generate_audit_index.py writes LIVE_AUDIT_INDEX.md
  # here), so review before pruning subfolders:
  #   rm -rf docs/engineering/audits docs/engineering/baseline_reviews

  # BIG space wins (see cleanup_safe.sh optional section):
  #   organism_brain_archive  (5.5 GB, prune to last 7 days)
  #   venv                    (2.1 GB, rebuild from requirements.lock)
  #   logs/                   (383 MB)   artifacts/ (149 MB)
----------------------------------------------------------------------
EOF
