"""Initial migration: users, orders, executions, outbox

Revision ID: 706e00fe1a28
Revises:
Create Date: 2025-09-28 17:24:33.410543

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '706e00fe1a28'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create users table FIRST (before tables with FK to users)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True, server_default=sa.text('true')),
    sa.Column('is_superuser', sa.Boolean(), nullable=True, server_default=sa.text('false')),
    sa.Column('created_at', sa.DateTime(timezone=False), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=False), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('roles', sa.ARRAY(sa.String()), nullable=False, server_default='{}'),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True, server_default='0'),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('hash_chain', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_action_ts', 'audit_logs', ['action', 'ts'], unique=False)
    op.create_index('ix_audit_logs_actor_ts', 'audit_logs', ['actor', 'ts'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity'], unique=False)
    op.create_index('ix_audit_logs_entity_ts', 'audit_logs', ['entity', 'ts'], unique=False)
    op.create_index('ix_audit_logs_ts', 'audit_logs', ['ts'], unique=False)
    op.create_table('model_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_registry')),
    sa.UniqueConstraint('name', 'version', name='uq_model_registry_name_version')
    )
    op.create_index('ix_model_registry_active', 'model_registry', ['active'], unique=False)
    op.create_index(op.f('ix_model_registry_name'), 'model_registry', ['name'], unique=False)
    op.create_index('ix_model_registry_name_version', 'model_registry', ['name', 'version'], unique=False)
    op.create_index(op.f('ix_model_registry_version'), 'model_registry', ['version'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('qty', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('tif', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_broker_order_id'), 'orders', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_orders_client_idempotency_key'), 'orders', ['client_idempotency_key'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index('ix_orders_submitted_at', 'orders', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_index('ix_orders_symbol_status', 'orders', ['symbol', 'status'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='outbox_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events'))
    )
    op.create_index('ix_outbox_created_at', 'outbox_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_next_attempt_at'), 'outbox_events', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_events_topic'), 'outbox_events', ['topic'], unique=False)
    op.create_index('ix_outbox_status_next_attempt', 'outbox_events', ['status', 'next_attempt_at'], unique=False)
    op.create_index('ix_outbox_topic_status', 'outbox_events', ['topic', 'status'], unique=False)
    op.create_table('positions',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('avg_price', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('realized_pnl', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('symbol', name=op.f('pk_positions'))
    )
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('strength', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.Column('confidence', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.Column('target_price', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('stop_loss', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('strategy', sa.String(length=100), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    op.create_index('ix_signals_confidence_strength', 'signals', ['confidence', 'strength'], unique=False)
    op.create_index('ix_signals_created_at', 'signals', ['created_at'], unique=False)
    op.create_index('ix_signals_expiry', 'signals', ['expiry'], unique=False)
    op.create_index(op.f('ix_signals_model_name'), 'signals', ['model_name'], unique=False)
    op.create_index(op.f('ix_signals_signal_type'), 'signals', ['signal_type'], unique=False)
    op.create_index('ix_signals_signal_type_direction', 'signals', ['signal_type', 'direction'], unique=False)
    op.create_index(op.f('ix_signals_strategy'), 'signals', ['strategy'], unique=False)
    op.create_index('ix_signals_strategy_ts', 'signals', ['strategy', 'ts'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_index('ix_signals_symbol_model', 'signals', ['symbol', 'model_name'], unique=False)
    op.create_index('ix_signals_symbol_ts', 'signals', ['symbol', 'ts'], unique=False)
    op.create_index(op.f('ix_signals_ts'), 'signals', ['ts'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('fill_qty', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('fill_price', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_executions_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions'))
    )
    op.create_index(op.f('ix_executions_order_id'), 'executions', ['order_id'], unique=False)
    op.create_index('ix_executions_order_ts', 'executions', ['order_id', 'ts'], unique=False)
    op.create_index('ix_executions_ts', 'executions', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_executions_ts', table_name='executions')
    op.drop_index('ix_executions_order_ts', table_name='executions')
    op.drop_index(op.f('ix_executions_order_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_signals_ts'), table_name='signals')
    op.drop_index('ix_signals_symbol_ts', table_name='signals')
    op.drop_index('ix_signals_symbol_model', table_name='signals')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index('ix_signals_strategy_ts', table_name='signals')
    op.drop_index(op.f('ix_signals_strategy'), table_name='signals')
    op.drop_index('ix_signals_signal_type_direction', table_name='signals')
    op.drop_index(op.f('ix_signals_signal_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_model_name'), table_name='signals')
    op.drop_index('ix_signals_expiry', table_name='signals')
    op.drop_index('ix_signals_created_at', table_name='signals')
    op.drop_index('ix_signals_confidence_strength', table_name='signals')
    op.drop_table('signals')
    op.drop_table('positions')
    op.drop_index('ix_outbox_topic_status', table_name='outbox_events')
    op.drop_index('ix_outbox_status_next_attempt', table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_topic'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_next_attempt_at'), table_name='outbox_events')
    op.drop_index('ix_outbox_created_at', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index('ix_orders_symbol_status', table_name='orders')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index('ix_orders_submitted_at', table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_idempotency_key'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_model_registry_version'), table_name='model_registry')
    op.drop_index('ix_model_registry_name_version', table_name='model_registry')
    op.drop_index(op.f('ix_model_registry_name'), table_name='model_registry')
    op.drop_index('ix_model_registry_active', table_name='model_registry')
    op.drop_table('model_registry')
    op.drop_index('ix_audit_logs_ts', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_ts', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_ts', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_ts', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # Drop users table LAST (after tables with FK to users are dropped)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
